# Generated by Django 3.1 on 2020-08-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=150)),
                ('lastName', models.CharField(blank=True, max_length=150)),
                ('userName', models.CharField(blank=True, max_length=150)),
                ('AboutMe', models.CharField(max_length=200)),
                ('passWord', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('profilePicture', models.ImageField(upload_to='profilePictures/')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
