# Generated by Django 3.1 on 2020-08-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Activated',
            field=models.BooleanField(default=False),
        ),
    ]
